### ISSUE TITLE
Closed Captions SW decoding for hearing impaired

### ISSUE THREAD

**Issue by razzeee** [razzeee/xbmc-test#56]
**Reported by Gamester17 on 4 Oct 2003 11:14 UTC**

Closed Captions SW decoding for hearing impaired

This Request is for SW decoding of CC (line 21 dat) only!

Captions (SW decoding) for hearing impaired", meaning 
decoded and displayed by XBMC (no passthrough) so 
users who do not have a CC enabled TV or other CC 
reader can enjoy Closed Captions as well :)

Closed captioning (CC, or line 21 data) is a simple 
feature that is included in most US(NTSC) DVD-movies 
(VOB files), and some DVD player pass-through that 
signal to a TV that supports CC the TV will decode and 
display them on demand (XBOXDASH.XBE MS dash DVD 
player also supports pass-throu of this in hardware), but 
this feature request is for it to be decoded in software 
and displayed/drawn on the screen by XBMC. For the 
hearing impaired CC are a must to fully enjoy DVD movies 
as they display text of audio that going on that only the 
hearing can hear and the normal subtitles do not show. 
PS! I believe CC is only broadly used in the U.S.A.

ore info on Closed Captions (CC, line 21 data):
http://www.robson.org/capfaq/technical.html

XBMP forum discussion thread for this feature/function:
www.xboxmediaplayer.de/cgi-bin/ib31/ikonboard.cgi?
act=ST;f=8;t=5135

FYI: A couple of Closed Caption FAQ's 

Are there captions on DVDs? 

Standards were created very late for DVDs, so there are 
several different ways to put captions on them. The 
most common approaches are to either embed Line-21- 
style captions in what are called the "user bits," or to 
use "subpictures" to display captions that look like 
subtitles. Your DVD player must support the same 
method that was used to encode the DVD, although 
many DVDs use both of these methods. When using 
subtitles, DVDs support captioning in multiple languages. 

What's the difference between subtitles and captions? 

Generally speaking, subtitles are intended for hearing 
audiences and captions for deaf audiences. Subtitles 
may translate the dialog into a different language, but 
rarely show all of the audio. For example, captions show 
sound effects (e.g., "phone ringing" and "footsteps"), 
while subtitles don't. 

Migrated-From: http://trac.kodi.tv/ticket/56

**Comment by razzeee** [comment]
**Comment by gamester17 on 23 Sep 2004 14:03 UTC**

Logged In: YES 
user_id=630186

According to MPlayer's manual it supports SW decoding of CC:
http://www.mplayerhq.hu/DOCS/HTML/en/subosd.html

**Comment by razzeee** [comment]
**Comment by gamester17 on 18 Jan 2005 15:20 UTC**

Logged In: YES 
user_id=630186

There's an "C" open source (GPL) closed caption decoder at:
http://etvcookbook.org/reference/referenceplatform.html

and there is an GPL open source "C++" version available at:
http://www.koders.com/c++/fidD5E1B8D838372D90B37658DE9
CF5FAC65A378E45.aspx
http://www.koders.com/c/fid120D7F025E56C431D7435F78CCE
4D27F43AC21B5.aspx


@Darkie, will you pls look at this for the DVD-playback core?
PS! I've attached the above mentioned codes for reference.

**Comment by razzeee** [comment]
**Comment by gamester17 on 31 Jul 2005 12:25 UTC**

Logged In: YES 
user_id=630186

FYI, I submitted this request to libdvdnav and got his reply:

CC and SPU decoding/displaying if for the media player to do. 
libdvdnav is purly for controlling the dvd navigation, not the 
display.

You will need a separate mpeg2 decoder that can handle CC, 
and a separate SPU decoder for subpictures. Neither of these 
are included with libdvdnav. Please see some application like xine 
(http://xinehq.de) for a application that supports both SPU and 
CC.

**Comment by razzeee** [comment]
**Comment by gamester17 on 26 Sep 2005 17:03 UTC**

Logged In: YES 
user_id=630186

assigning to Carlos (a.k.a. CFS)

**Comment by razzeee** [comment]
**Comment by gamester17 on 10 Oct 2005 06:51 UTC**

Logged In: YES 
user_id=630186

@cfsmp3, any updates on this?, ...hope to see it in CVS soon :)

**Comment by razzeee** [comment]
**Comment by gamester17 on 30 Nov 2005 13:49 UTC**

Logged In: YES 
user_id=630186

FYI, ffdshow now feature some basic closed captions support

see ffdshow CVS => http://sourceforge.net/projects/ffdshow
(look in /ffdshow/src/subtitles, code is in C++ for Win32)

**Comment by razzeee** [comment]
**Comment by gamester17 on 30 Aug 2006 19:40 UTC**

Logged In: YES 
user_id=630186

@cfsmp3, have u given up on this? should it be re-assigned?

**Comment by razzeee** [comment]
**Comment by gamester17 on 30 Aug 2006 19:41 UTC**

Logged In: YES 
user_id=630186

@cfsmp3, have u given up on this? should it be re-assigned?

**Comment by razzeee** [comment]
**Comment by gamester17 on 18 Jul 2007 11:49 UTC**

Logged In: YES 
user_id=630186
Originator: YES

@cfsmp3, heard you were looking into Closed Captions again(?), have you made any progress? and is it for the the DVDPlayer core or for the MPlayer core? ...and is it for pass-through or software decoding/displaying?

**Comment by razzeee** [comment]
**Comment by cfsmp3 on 4 Aug 2007 16:56 UTC**

Logged In: YES 
user_id=642118
Originator: NO

Gamester, we don't need a closed caption decoder, we already have one (ccextractor.sourceforge.net). What I need is the user data part of the MPEG files. I saw that xbmc's mpeg2lib has a user data part, but not the official mpeg2lib (or I missed it).

From the user data, the rest is already done. I decode closed captions just fine, and emulate the display.

**Comment by razzeee** [comment]
**Modified by sho on 8 Aug 2008 17:03 UTC**

**Comment by razzeee** [comment]
**Modified by vdrfan on 23 Nov 2009 18:56 UTC**

**Comment by razzeee** [comment]
**Modified by sho on 11 Jul 2010 13:20 UTC**

**Comment by razzeee** [comment]
**Modified by sho on 21 Feb 2011 13:54 UTC**

**Comment by razzeee** [comment]
**Modified by Martijn on 17 Sep 2012 15:53 UTC**

**Comment by razzeee** [comment]
**Modified by sho on 18 Sep 2012 20:51 UTC**

**Comment by cfsmp3** [comment]
Just noticed this thread.

All my efforts on closed captioning support are in CCExtractor, which I
started many years ago and is still being developed and maintained.

The problem I found when trying to add captions supports to XBMC, which I
don't know if it's still true, is that CEA-608 is present (as user-data) in
the video stream in MPEG-2. And that doesn't work well with FFmpeg's
architecture in which a stream is (was?) expected to carry one thing only.

**Comment by razzeee** [comment]
Sorry for pinging you, this is just a test repo, trying to convert trac tickets to github issues.
